name: Bug Report
description: Report a problem with the EWT2026 infrastructure, website, or processes
title: "[BUG] [Brief Description]"
labels: ["bug", "needs-triage"]

body:
  - type: markdown
    attributes:
      value: |
        ## Bug Report

        Use this template to report issues with:
        - The EWT2026 repository or infrastructure
        - GitHub workflows or automation
        - Documentation errors
        - Process problems

        **Not for:** Code issues in participant submissions (those go in PR reviews)

  - type: dropdown
    id: bug-area
    attributes:
      label: What area is affected?
      options:
        - "Repository Structure"
        - "GitHub Actions/Workflows"
        - "Documentation (README, guidelines, etc.)"
        - "Issue Templates"
        - "PR Templates"
        - "CODEOWNERS"
        - "Website/GitHub Pages"
        - "Other"
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: Clear description of what's wrong
      placeholder: When I try to [action], [unexpected behavior] happens instead of [expected behavior]
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to Reproduce
      description: How can we reproduce this issue?
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: I expected...
    validations:
      required: true

  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual Behavior
      description: What actually happened?
      placeholder: Instead, what happened was...
    validations:
      required: true

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots or Logs
      description: If applicable, add screenshots or paste error logs
      placeholder: Paste screenshots or logs here
    validations:
      required: false

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Your environment details (if relevant)
      placeholder: |
        - Browser: Chrome 120
        - OS: macOS 14.1
        - GitHub account type: Free/Pro/etc.
    validations:
      required: false

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Any other information that might be helpful
    validations:
      required: false
