name: General Question
description: Ask a general question about EWT2026 (not project-specific)
title: "[QUESTION] [Brief Description]"
labels: ["question"]

body:
  - type: markdown
    attributes:
      value: |
        ## General Question

        For questions about:
        - How EWT2026 works
        - Participation guidelines
        - Review process
        - Community guidelines
        - Anything else not covered by other templates

        **Note:** For project-specific questions, use the "Project Question" template instead.

  - type: dropdown
    id: question-category
    attributes:
      label: Question Category
      options:
        - "How to Participate"
        - "Review Process"
        - "Timeline and Deadlines"
        - "Submission Guidelines"
        - "Community Guidelines"
        - "Technical Setup"
        - "Other"
    validations:
      required: true

  - type: textarea
    id: question
    attributes:
      label: Your Question
      description: What would you like to know?
      placeholder: I'd like to understand...
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Any additional information that might help us answer
      placeholder: |
        - What you've already tried to find the answer
        - Why you're asking
        - Specific scenario or use case
    validations:
      required: false
